# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_reg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(700, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(700, 600))
        mainWindow.setMaximumSize(QtCore.QSize(700, 600))
        mainWindow.setStyleSheet(_fromUtf8("#mainWindow\n"
"{\n"
"background:#46406E;\n"
"}"))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelItemInfo = QtGui.QLabel(self.centralwidget)
        self.labelItemInfo.setObjectName(_fromUtf8("labelItemInfo"))
        self.verticalLayout.addWidget(self.labelItemInfo)
        self.groupBoxAllItems = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxAllItems.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAllItems.sizePolicy().hasHeightForWidth())
        self.groupBoxAllItems.setSizePolicy(sizePolicy)
        self.groupBoxAllItems.setCheckable(True)
        self.groupBoxAllItems.setChecked(True)
        self.groupBoxAllItems.setObjectName(_fromUtf8("groupBoxAllItems"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxAllItems)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEditBrandSearch = QtGui.QLineEdit(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBrandSearch.sizePolicy().hasHeightForWidth())
        self.lineEditBrandSearch.setSizePolicy(sizePolicy)
        self.lineEditBrandSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditBrandSearch.setObjectName(_fromUtf8("lineEditBrandSearch"))
        self.verticalLayout_4.addWidget(self.lineEditBrandSearch)
        self.lineEditModelSearch = QtGui.QLineEdit(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditModelSearch.sizePolicy().hasHeightForWidth())
        self.lineEditModelSearch.setSizePolicy(sizePolicy)
        self.lineEditModelSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditModelSearch.setObjectName(_fromUtf8("lineEditModelSearch"))
        self.verticalLayout_4.addWidget(self.lineEditModelSearch)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listViewModelSearch = QtGui.QListWidget(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewModelSearch.sizePolicy().hasHeightForWidth())
        self.listViewModelSearch.setSizePolicy(sizePolicy)
        self.listViewModelSearch.setObjectName(_fromUtf8("listViewModelSearch"))
        self.horizontalLayout_3.addWidget(self.listViewModelSearch)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widgetPic = QtGui.QWidget(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPic.sizePolicy().hasHeightForWidth())
        self.widgetPic.setSizePolicy(sizePolicy)
        self.widgetPic.setObjectName(_fromUtf8("widgetPic"))
        self.verticalLayout_2.addWidget(self.widgetPic)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lineEditUnavailableType = QtGui.QLineEdit(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUnavailableType.sizePolicy().hasHeightForWidth())
        self.lineEditUnavailableType.setSizePolicy(sizePolicy)
        self.lineEditUnavailableType.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditUnavailableType.setObjectName(_fromUtf8("lineEditUnavailableType"))
        self.verticalLayout_4.addWidget(self.lineEditUnavailableType)
        self.label_6 = QtGui.QLabel(self.groupBoxAllItems)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.textEditProblemDescription = QtGui.QTextEdit(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditProblemDescription.sizePolicy().hasHeightForWidth())
        self.textEditProblemDescription.setSizePolicy(sizePolicy)
        self.textEditProblemDescription.setMinimumSize(QtCore.QSize(200, 50))
        self.textEditProblemDescription.setMaximumSize(QtCore.QSize(200, 50))
        self.textEditProblemDescription.setObjectName(_fromUtf8("textEditProblemDescription"))
        self.verticalLayout_4.addWidget(self.textEditProblemDescription)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBoxAllItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditCurrentBill = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCurrentBill.sizePolicy().hasHeightForWidth())
        self.lineEditCurrentBill.setSizePolicy(sizePolicy)
        self.lineEditCurrentBill.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditCurrentBill.setObjectName(_fromUtf8("lineEditCurrentBill"))
        self.horizontalLayout_2.addWidget(self.lineEditCurrentBill)
        self.checkBoxPendBill = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxPendBill.sizePolicy().hasHeightForWidth())
        self.checkBoxPendBill.setSizePolicy(sizePolicy)
        self.checkBoxPendBill.setObjectName(_fromUtf8("checkBoxPendBill"))
        self.horizontalLayout_2.addWidget(self.checkBoxPendBill)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditBalanceBill = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBalanceBill.sizePolicy().hasHeightForWidth())
        self.lineEditBalanceBill.setSizePolicy(sizePolicy)
        self.lineEditBalanceBill.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditBalanceBill.setObjectName(_fromUtf8("lineEditBalanceBill"))
        self.horizontalLayout_4.addWidget(self.lineEditBalanceBill)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBoxAllItems)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushButtonSave = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSave.setSizePolicy(sizePolicy)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout_6.addWidget(self.pushButtonSave)
        self.pushButtonReset = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.horizontalLayout_6.addWidget(self.pushButtonReset)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Register New Job", None))
        self.label.setText(_translate("mainWindow", "Item Information", None))
        self.labelItemInfo.setText(_translate("mainWindow", "Item for customer", None))
        self.groupBoxAllItems.setTitle(_translate("mainWindow", "Item (Uncheck this box to delete)", None))
        self.lineEditBrandSearch.setStatusTip(_translate("mainWindow", "Seach for available brands", None))
        self.lineEditBrandSearch.setPlaceholderText(_translate("mainWindow", "Search Brand", None))
        self.lineEditModelSearch.setStatusTip(_translate("mainWindow", "Search for available models", None))
        self.lineEditModelSearch.setPlaceholderText(_translate("mainWindow", "Search Model (Select Brand First)", None))
        self.lineEditUnavailableType.setStatusTip(_translate("mainWindow", "Specify if item is not available", None))
        self.lineEditUnavailableType.setPlaceholderText(_translate("mainWindow", "Unavailable Type", None))
        self.label_6.setText(_translate("mainWindow", "Brief Problem Description:", None))
        self.textEditProblemDescription.setStatusTip(_translate("mainWindow", "Problem of Item", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "Bill", None))
        self.lineEditCurrentBill.setStatusTip(_translate("mainWindow", "Amount charged for job", None))
        self.lineEditCurrentBill.setPlaceholderText(_translate("mainWindow", "Bill (Amount only)", None))
        self.checkBoxPendBill.setStatusTip(_translate("mainWindow", "Pend this bill", None))
        self.checkBoxPendBill.setText(_translate("mainWindow", "Pend Bill", None))
        self.lineEditBalanceBill.setStatusTip(_translate("mainWindow", "Amount Paid", None))
        self.lineEditBalanceBill.setPlaceholderText(_translate("mainWindow", "Amount Paid", None))
        self.pushButtonSave.setStatusTip(_translate("mainWindow", "Add", None))
        self.pushButtonSave.setText(_translate("mainWindow", "Add", None))
        self.pushButtonReset.setStatusTip(_translate("mainWindow", "Reset all values", None))
        self.pushButtonReset.setText(_translate("mainWindow", "Reset", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

