# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_front.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/W1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet(_fromUtf8("#centralwidget{\n"
"    border-image: url(:/backgrounds/images/backgounds/_8.jpg);\n"
"}"))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 130, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setVerticalSpacing(130)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonAddRepairs = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAddRepairs.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonAddRepairs.setMaximumSize(QtCore.QSize(200, 100))
        self.pushButtonAddRepairs.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddRepairs.setFont(font)
        self.pushButtonAddRepairs.setStyleSheet(_fromUtf8(""))
        self.pushButtonAddRepairs.setInputMethodHints(QtCore.Qt.ImhNone)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddRepairs.setIcon(icon1)
        self.pushButtonAddRepairs.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonAddRepairs.setObjectName(_fromUtf8("pushButtonAddRepairs"))
        self.gridLayout.addWidget(self.pushButtonAddRepairs, 0, 0, 1, 1)
        self.pushButtonMessageCust = QtGui.QPushButton(self.centralwidget)
        self.pushButtonMessageCust.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonMessageCust.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMessageCust.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/envelope2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMessageCust.setIcon(icon2)
        self.pushButtonMessageCust.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonMessageCust.setObjectName(_fromUtf8("pushButtonMessageCust"))
        self.gridLayout.addWidget(self.pushButtonMessageCust, 0, 2, 1, 1)
        self.pushButtonModifyRepairs = QtGui.QPushButton(self.centralwidget)
        self.pushButtonModifyRepairs.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonModifyRepairs.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonModifyRepairs.setFont(font)
        self.pushButtonModifyRepairs.setStyleSheet(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonModifyRepairs.setIcon(icon3)
        self.pushButtonModifyRepairs.setIconSize(QtCore.QSize(40, 50))
        self.pushButtonModifyRepairs.setCheckable(False)
        self.pushButtonModifyRepairs.setAutoRepeat(False)
        self.pushButtonModifyRepairs.setAutoDefault(False)
        self.pushButtonModifyRepairs.setDefault(False)
        self.pushButtonModifyRepairs.setFlat(False)
        self.pushButtonModifyRepairs.setObjectName(_fromUtf8("pushButtonModifyRepairs"))
        self.gridLayout.addWidget(self.pushButtonModifyRepairs, 0, 1, 1, 1)
        self.pushButtonTransaction = QtGui.QPushButton(self.centralwidget)
        self.pushButtonTransaction.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonTransaction.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTransaction.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/naira.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonTransaction.setIcon(icon4)
        self.pushButtonTransaction.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonTransaction.setObjectName(_fromUtf8("pushButtonTransaction"))
        self.gridLayout.addWidget(self.pushButtonTransaction, 1, 0, 1, 1)
        self.pushButtonAdminFront = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAdminFront.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonAdminFront.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAdminFront.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdminFront.setIcon(icon5)
        self.pushButtonAdminFront.setIconSize(QtCore.QSize(40, 50))
        self.pushButtonAdminFront.setObjectName(_fromUtf8("pushButtonAdminFront"))
        self.gridLayout.addWidget(self.pushButtonAdminFront, 1, 1, 1, 1)
        self.pushButtonPartsFront = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPartsFront.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButtonPartsFront.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPartsFront.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/headphone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPartsFront.setIcon(icon6)
        self.pushButtonPartsFront.setIconSize(QtCore.QSize(60, 50))
        self.pushButtonPartsFront.setObjectName(_fromUtf8("pushButtonPartsFront"))
        self.gridLayout.addWidget(self.pushButtonPartsFront, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxFullscreen = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxFullscreen.setObjectName(_fromUtf8("checkBoxFullscreen"))
        self.horizontalLayout.addWidget(self.checkBoxFullscreen)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonDatabase = QtGui.QPushButton(self.centralwidget)
        self.pushButtonDatabase.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDatabase.setIcon(icon7)
        self.pushButtonDatabase.setObjectName(_fromUtf8("pushButtonDatabase"))
        self.horizontalLayout.addWidget(self.pushButtonDatabase)
        self.pushButtonNewData = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNewData.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/internet_earth.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNewData.setIcon(icon8)
        self.pushButtonNewData.setObjectName(_fromUtf8("pushButtonNewData"))
        self.horizontalLayout.addWidget(self.pushButtonNewData)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.loadingLayout = QtGui.QHBoxLayout()
        self.loadingLayout.setContentsMargins(-1, 0, -1, -1)
        self.loadingLayout.setObjectName(_fromUtf8("loadingLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.loadingLayout.addItem(spacerItem3)
        self.labelFetchingInfo = QtGui.QLabel(self.centralwidget)
        self.labelFetchingInfo.setStyleSheet(_fromUtf8("color: rgb(170, 167, 157);"))
        self.labelFetchingInfo.setObjectName(_fromUtf8("labelFetchingInfo"))
        self.loadingLayout.addWidget(self.labelFetchingInfo)
        self.verticalLayout_2.addLayout(self.loadingLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBackupDatabase = QtGui.QAction(MainWindow)
        self.actionBackupDatabase.setObjectName(_fromUtf8("actionBackupDatabase"))
        self.actionNewData = QtGui.QAction(MainWindow)
        self.actionNewData.setObjectName(_fromUtf8("actionNewData"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "WEBTY SOLUTIONS", None))
        self.pushButtonAddRepairs.setStatusTip(_translate("MainWindow", "Add new customers and repair jobs", None))
        self.pushButtonAddRepairs.setText(_translate("MainWindow", "ADD", None))
        self.pushButtonMessageCust.setStatusTip(_translate("MainWindow", "Send sms messages", None))
        self.pushButtonMessageCust.setText(_translate("MainWindow", "MESSAGE", None))
        self.pushButtonModifyRepairs.setStatusTip(_translate("MainWindow", "Search, update and delete customers and repair jobs", None))
        self.pushButtonModifyRepairs.setText(_translate("MainWindow", "SEARCH", None))
        self.pushButtonTransaction.setStatusTip(_translate("MainWindow", "Money spent and received", None))
        self.pushButtonTransaction.setText(_translate("MainWindow", "TRANSACTIONS", None))
        self.pushButtonAdminFront.setStatusTip(_translate("MainWindow", "Admin portal", None))
        self.pushButtonAdminFront.setText(_translate("MainWindow", "ADMIN", None))
        self.pushButtonPartsFront.setStatusTip(_translate("MainWindow", "All spare parts available ", None))
        self.pushButtonPartsFront.setText(_translate("MainWindow", "PARTS", None))
        self.checkBoxFullscreen.setText(_translate("MainWindow", "Toggle Fullscreen", None))
        self.pushButtonDatabase.setStatusTip(_translate("MainWindow", "Backup and Restore Database", None))
        self.pushButtonNewData.setStatusTip(_translate("MainWindow", "Fetch new data from internet", None))
        self.labelFetchingInfo.setText(_translate("MainWindow", "Fetching new data from internet...", None))
        self.actionBackupDatabase.setText(_translate("MainWindow", "Backup/Restore Database", None))
        self.actionBackupDatabase.setStatusTip(_translate("MainWindow", "Backup and restore database", None))
        self.actionNewData.setText(_translate("MainWindow", "Fetch New Data", None))
        self.actionNewData.setStatusTip(_translate("MainWindow", "Fetch new phone data from internet", None))

import custom_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

