# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_searchForm(object):
    def setupUi(self, searchForm):
        searchForm.setObjectName(_fromUtf8("searchForm"))
        searchForm.setWindowModality(QtCore.Qt.WindowModal)
        searchForm.resize(1200, 500)
        searchForm.setMinimumSize(QtCore.QSize(1200, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        searchForm.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(searchForm)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditItemSearch = QtGui.QLineEdit(self.centralwidget)
        self.lineEditItemSearch.setObjectName(_fromUtf8("lineEditItemSearch"))
        self.horizontalLayout.addWidget(self.lineEditItemSearch)
        self.comboBoxItemSearch = QtGui.QComboBox(self.centralwidget)
        self.comboBoxItemSearch.setObjectName(_fromUtf8("comboBoxItemSearch"))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.comboBoxItemSearch.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxItemSearch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetItemSearch = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetItemSearch.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetItemSearch.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetItemSearch.setObjectName(_fromUtf8("tableWidgetItemSearch"))
        self.tableWidgetItemSearch.setColumnCount(11)
        self.tableWidgetItemSearch.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetItemSearch.setHorizontalHeaderItem(10, item)
        self.verticalLayout.addWidget(self.tableWidgetItemSearch)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditCustomerSearch = QtGui.QLineEdit(self.centralwidget)
        self.lineEditCustomerSearch.setObjectName(_fromUtf8("lineEditCustomerSearch"))
        self.horizontalLayout_2.addWidget(self.lineEditCustomerSearch)
        self.comboBoxCustomerSearch = QtGui.QComboBox(self.centralwidget)
        self.comboBoxCustomerSearch.setObjectName(_fromUtf8("comboBoxCustomerSearch"))
        self.comboBoxCustomerSearch.addItem(_fromUtf8(""))
        self.comboBoxCustomerSearch.addItem(_fromUtf8(""))
        self.comboBoxCustomerSearch.addItem(_fromUtf8(""))
        self.comboBoxCustomerSearch.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBoxCustomerSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidgetCustomerSearch = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetCustomerSearch.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetCustomerSearch.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetCustomerSearch.setObjectName(_fromUtf8("tableWidgetCustomerSearch"))
        self.tableWidgetCustomerSearch.setColumnCount(5)
        self.tableWidgetCustomerSearch.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCustomerSearch.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCustomerSearch.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCustomerSearch.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCustomerSearch.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCustomerSearch.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidgetCustomerSearch)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonAddItem = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAddItem.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonAddItem.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonAddItem.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/plus.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddItem.setIcon(icon1)
        self.pushButtonAddItem.setObjectName(_fromUtf8("pushButtonAddItem"))
        self.horizontalLayout_3.addWidget(self.pushButtonAddItem)
        self.pushButtonSave = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon2)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        searchForm.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(searchForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        searchForm.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(searchForm)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        searchForm.setStatusBar(self.statusbar)

        self.retranslateUi(searchForm)
        QtCore.QMetaObject.connectSlotsByName(searchForm)

    def retranslateUi(self, searchForm):
        searchForm.setWindowTitle(_translate("searchForm", "SEARCH", None))
        self.comboBoxItemSearch.setItemText(0, _translate("searchForm", "ID", None))
        self.comboBoxItemSearch.setItemText(1, _translate("searchForm", "MAKE & MODEL", None))
        self.comboBoxItemSearch.setItemText(2, _translate("searchForm", "IMEI/S.No", None))
        self.comboBoxItemSearch.setItemText(3, _translate("searchForm", "KNOWN FAULTS", None))
        self.comboBoxItemSearch.setItemText(4, _translate("searchForm", "ADDITIONAL DETAILS", None))
        self.comboBoxItemSearch.setItemText(5, _translate("searchForm", "BILL", None))
        self.comboBoxItemSearch.setItemText(6, _translate("searchForm", "AMOUNT PAID", None))
        self.comboBoxItemSearch.setItemText(7, _translate("searchForm", "STATUS", None))
        self.comboBoxItemSearch.setItemText(8, _translate("searchForm", "DATE IN", None))
        self.comboBoxItemSearch.setItemText(9, _translate("searchForm", "DATE OUT", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(0)
        item.setText(_translate("searchForm", "ID", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(1)
        item.setText(_translate("searchForm", "MAKE & MODEL", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(2)
        item.setText(_translate("searchForm", "IMEI/S. No", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(3)
        item.setText(_translate("searchForm", "KNOWN FAULTS", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(4)
        item.setText(_translate("searchForm", "ADDITIONAL DETAILS", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(5)
        item.setText(_translate("searchForm", "BILL", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(6)
        item.setText(_translate("searchForm", "AMOUNT PAID", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(7)
        item.setText(_translate("searchForm", "STATUS", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(8)
        item.setText(_translate("searchForm", "DATE IN", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(9)
        item.setText(_translate("searchForm", "DATE OUT", None))
        item = self.tableWidgetItemSearch.horizontalHeaderItem(10)
        item.setText(_translate("searchForm", "CUSTID", None))
        self.comboBoxCustomerSearch.setItemText(0, _translate("searchForm", "ID", None))
        self.comboBoxCustomerSearch.setItemText(1, _translate("searchForm", "NAME", None))
        self.comboBoxCustomerSearch.setItemText(2, _translate("searchForm", "MOBILE", None))
        self.comboBoxCustomerSearch.setItemText(3, _translate("searchForm", "DATE ADDED", None))
        item = self.tableWidgetCustomerSearch.horizontalHeaderItem(0)
        item.setText(_translate("searchForm", "ID", None))
        item = self.tableWidgetCustomerSearch.horizontalHeaderItem(1)
        item.setText(_translate("searchForm", "NAME", None))
        item = self.tableWidgetCustomerSearch.horizontalHeaderItem(2)
        item.setText(_translate("searchForm", "MOBILE", None))
        item = self.tableWidgetCustomerSearch.horizontalHeaderItem(3)
        item.setText(_translate("searchForm", "MOBILE 2", None))
        item = self.tableWidgetCustomerSearch.horizontalHeaderItem(4)
        item.setText(_translate("searchForm", "DATE ADDED", None))

import custom_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    searchForm = QtGui.QMainWindow()
    ui = Ui_searchForm()
    ui.setupUi(searchForm)
    searchForm.show()
    sys.exit(app.exec_())

