# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_cust_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_updateForm(object):
    def setupUi(self, updateForm):
        updateForm.setObjectName(_fromUtf8("updateForm"))
        updateForm.setWindowModality(QtCore.Qt.WindowModal)
        updateForm.resize(860, 550)
        updateForm.setMinimumSize(QtCore.QSize(860, 550))
        updateForm.setMaximumSize(QtCore.QSize(860, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        updateForm.setWindowIcon(icon)
        updateForm.setStyleSheet(_fromUtf8("#updateForm{\n"
"    border-image: url(:/backgrounds/images/backgounds/_8.jpg);\n"
"}"))
        self.centralwidget = QtGui.QWidget(updateForm)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(10, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditSearchCustId = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSearchCustId.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditSearchCustId.setObjectName(_fromUtf8("lineEditSearchCustId"))
        self.horizontalLayout.addWidget(self.lineEditSearchCustId)
        self.lineEditSearchCustomer = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.lineEditSearchCustomer.setFont(font)
        self.lineEditSearchCustomer.setToolTip(_fromUtf8(""))
        self.lineEditSearchCustomer.setObjectName(_fromUtf8("lineEditSearchCustomer"))
        self.horizontalLayout.addWidget(self.lineEditSearchCustomer)
        self.comboBoxSearchChoice = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSearchChoice.sizePolicy().hasHeightForWidth())
        self.comboBoxSearchChoice.setSizePolicy(sizePolicy)
        self.comboBoxSearchChoice.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxSearchChoice.setFont(font)
        self.comboBoxSearchChoice.setStatusTip(_fromUtf8(""))
        self.comboBoxSearchChoice.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxSearchChoice.setObjectName(_fromUtf8("comboBoxSearchChoice"))
        self.comboBoxSearchChoice.addItem(_fromUtf8(""))
        self.comboBoxSearchChoice.addItem(_fromUtf8(""))
        self.comboBoxSearchChoice.addItem(_fromUtf8(""))
        self.comboBoxSearchChoice.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxSearchChoice)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetRepairJob = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetRepairJob.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidgetRepairJob.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidgetRepairJob.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetRepairJob.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetRepairJob.setObjectName(_fromUtf8("tableWidgetRepairJob"))
        self.tableWidgetRepairJob.setColumnCount(9)
        self.tableWidgetRepairJob.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRepairJob.setHorizontalHeaderItem(8, item)
        self.tableWidgetRepairJob.horizontalHeader().setVisible(True)
        self.tableWidgetRepairJob.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetRepairJob)
        self.tableWidgetCust = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetCust.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidgetCust.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidgetCust.setAlternatingRowColors(True)
        self.tableWidgetCust.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetCust.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetCust.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetCust.setShowGrid(True)
        self.tableWidgetCust.setCornerButtonEnabled(True)
        self.tableWidgetCust.setObjectName(_fromUtf8("tableWidgetCust"))
        self.tableWidgetCust.setColumnCount(5)
        self.tableWidgetCust.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCust.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCust.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCust.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCust.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCust.setHorizontalHeaderItem(4, item)
        self.tableWidgetCust.horizontalHeader().setVisible(True)
        self.tableWidgetCust.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetCust.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetCust.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidgetCust)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonReturned = QtGui.QPushButton(self.centralwidget)
        self.pushButtonReturned.setEnabled(False)
        self.pushButtonReturned.setMinimumSize(QtCore.QSize(37, 33))
        self.pushButtonReturned.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/returned.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonReturned.setIcon(icon1)
        self.pushButtonReturned.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonReturned.setObjectName(_fromUtf8("pushButtonReturned"))
        self.horizontalLayout_2.addWidget(self.pushButtonReturned)
        self.pushButtonUnfixed = QtGui.QPushButton(self.centralwidget)
        self.pushButtonUnfixed.setEnabled(False)
        self.pushButtonUnfixed.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonUnfixed.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/bad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUnfixed.setIcon(icon2)
        self.pushButtonUnfixed.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonUnfixed.setObjectName(_fromUtf8("pushButtonUnfixed"))
        self.horizontalLayout_2.addWidget(self.pushButtonUnfixed)
        self.pushButtonFixed = QtGui.QPushButton(self.centralwidget)
        self.pushButtonFixed.setEnabled(False)
        self.pushButtonFixed.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonFixed.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFixed.setIcon(icon3)
        self.pushButtonFixed.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonFixed.setObjectName(_fromUtf8("pushButtonFixed"))
        self.horizontalLayout_2.addWidget(self.pushButtonFixed)
        self.pushButtonDelete = QtGui.QPushButton(self.centralwidget)
        self.pushButtonDelete.setEnabled(False)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonDelete.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelete.setIcon(icon4)
        self.pushButtonDelete.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.pushButtonAdd = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAdd.setEnabled(False)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonAdd.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/plus.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon5)
        self.pushButtonAdd.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout_2.addWidget(self.pushButtonAdd)
        self.pushButtonUpdate = QtGui.QPushButton(self.centralwidget)
        self.pushButtonUpdate.setEnabled(False)
        self.pushButtonUpdate.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonUpdate.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUpdate.setIcon(icon6)
        self.pushButtonUpdate.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.horizontalLayout_2.addWidget(self.pushButtonUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        updateForm.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(updateForm)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        updateForm.setStatusBar(self.statusbar)

        self.retranslateUi(updateForm)
        QtCore.QMetaObject.connectSlotsByName(updateForm)

    def retranslateUi(self, updateForm):
        updateForm.setWindowTitle(_translate("updateForm", "SEARCH", None))
        self.label.setText(_translate("updateForm", "ID", None))
        self.lineEditSearchCustId.setPlaceholderText(_translate("updateForm", "Search Id", None))
        self.lineEditSearchCustomer.setStatusTip(_translate("updateForm", "Search Customer", None))
        self.lineEditSearchCustomer.setPlaceholderText(_translate("updateForm", "Search Customer", None))
        self.comboBoxSearchChoice.setItemText(0, _translate("updateForm", "Customer Name", None))
        self.comboBoxSearchChoice.setItemText(1, _translate("updateForm", "Customer Mobile", None))
        self.comboBoxSearchChoice.setItemText(2, _translate("updateForm", "Item Name", None))
        self.comboBoxSearchChoice.setItemText(3, _translate("updateForm", "Date", None))
        self.tableWidgetRepairJob.setSortingEnabled(True)
        item = self.tableWidgetRepairJob.horizontalHeaderItem(0)
        item.setText(_translate("updateForm", "id", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(1)
        item.setText(_translate("updateForm", "Item", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(2)
        item.setText(_translate("updateForm", "Customer Id", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(3)
        item.setText(_translate("updateForm", "Bill", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(4)
        item.setText(_translate("updateForm", "Info", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(5)
        item.setText(_translate("updateForm", "Paid", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(6)
        item.setText(_translate("updateForm", "Status", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(7)
        item.setText(_translate("updateForm", "Date Received", None))
        item = self.tableWidgetRepairJob.horizontalHeaderItem(8)
        item.setText(_translate("updateForm", "Date Returned", None))
        self.tableWidgetCust.setSortingEnabled(True)
        item = self.tableWidgetCust.horizontalHeaderItem(0)
        item.setText(_translate("updateForm", "id", None))
        item = self.tableWidgetCust.horizontalHeaderItem(1)
        item.setText(_translate("updateForm", "Name", None))
        item = self.tableWidgetCust.horizontalHeaderItem(2)
        item.setText(_translate("updateForm", "Mobile", None))
        item = self.tableWidgetCust.horizontalHeaderItem(3)
        item.setText(_translate("updateForm", "Mobile2", None))
        item = self.tableWidgetCust.horizontalHeaderItem(4)
        item.setText(_translate("updateForm", "Date Added", None))
        self.pushButtonReturned.setStatusTip(_translate("updateForm", "Item returned", None))
        self.pushButtonUnfixed.setStatusTip(_translate("updateForm", "Unfixable", None))
        self.pushButtonFixed.setStatusTip(_translate("updateForm", "Fixed", None))
        self.pushButtonDelete.setStatusTip(_translate("updateForm", "Delete", None))
        self.pushButtonAdd.setStatusTip(_translate("updateForm", "Add Repair Job", None))
        self.pushButtonUpdate.setStatusTip(_translate("updateForm", "Update", None))

import custom_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    updateForm = QtGui.QMainWindow()
    ui = Ui_updateForm()
    ui.setupUi(updateForm)
    updateForm.show()
    sys.exit(app.exec_())

